name: Send Slack Message for approval

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the action on

jobs:
  send-message:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Send Slack Message
      run: |
        curl --location 'https://slack.com/api/chat.postMessage' \
        --header 'Content-type: application/json' \
        --header 'Authorization: Bearer ${{ secrets.SLACK_BOT_TOKEN }}' \
        --data '{
            "channel": "#aws-deployments",
            "blocks": [
                {
                    "type": "section",
                    "text": {
                        "type": "mrkdwn",
                        "text": "Hello <@U048NU0SXCJ>! Lambda Function deployment has been triggered. Do you want to approve the pipeline? Sayonara!"
                    }
                },
                {
                    "type":"actions",
                    "elements":[
                        {
                            "type": "button",
                            "text": {
                                "type": "plain_text",
                                "text": "Yes"
                            },
                            "style": "primary",
                            "action_id": "yes_button"
                        }
                    ]
                },
                {
                    "type": "actions", 
                    "elements": [
                        {
                            "type": "button",
                            "text": {
                                "type": "plain_text",
                                "text": "No"
                            },
                            "style": "danger",
                            "action_id": "no_button"
                        }
                    ]
                }
            ]
        }'
