name: PlacesLambda

on:
  push:
    branches:
      - main

jobs:
  update-lambda:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install AWS CLI
      run: |
        pip install awscli

    - name: Configure AWS CLI
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region ${{ secrets.AWS_REGION }}

    - name: Update Lambda Function
      run: |
        aws lambda update-function-code --function-name ratingsInfo --zip-file fileb://lambda_function.py.zip

