name: Send Slack Message via Bot

on:
  push:
    branches:
      - main

jobs:
  send-slack-message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send Slack Message
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        run: |
          curl -X POST -H "Content-type: application/json" \
               -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
               --data '{
                 "channel": "#aws-deployments",
                 "text": "Hello <@U048NU0SXCJ> , a deployment has been triggered for Lambda Function. This is not an approval flow but just for intimation. Sayonara!"
               }' "https://slack.com/api/chat.postMessage"
